query GetSelfProjects($where: ProjectWhereInput) {
  projects(where: $where) {
    id
    title
    description
    users {
      avatar
      id
    }
    owner {
      first_name
      avatar
      last_name
      id
    }
  }
}
